joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0

# Position Controllers ---------------------------------------

joint12_position_controller:
  type: position_controllers/JointPositionController
  joint: cadera_2
  pid: {p: 14, i: 0, d: 1}
joint22_position_controller:
  type: position_controllers/JointPositionController
  joint: hombro_2
  pid: {p: 14, i: 0, d: 1}
joint32_position_controller:
  type: position_controllers/JointPositionController
  joint: codo_2
  pid: {p: 14, i: 0, d: 5}
joint42_position_controller:
  type: position_controllers/JointPositionController
  joint: mano_2
  pid: {p: 14, i: 0, d: 1}
joint52_position_controller:
  type: position_controllers/JointPositionController
  joint: gripper0_2
  pid: {p: 5, i: 0.4, d: 2}
joint62_position_controller:
  type: position_controllers/JointPositionController
  joint: gripper1_2
  pid: {p: 4, i: 0.5, d: 2}
